---
name: Molecule
"on":
  workflow_call:
    inputs:
      molecule_image:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: gofrolist/molecule-action@v2
        env:
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_IMAGE: ${{ inputs.molecule_image }}
